# Generated by Django 2.2.8 on 2020-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_cities',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_constellations',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_stocks',
            field=models.TextField(default='[]'),
        ),
    ]
