# Generated by Django 2.2.8 on 2020-03-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0003_auto_20200303_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='nickname66666'),
        ),
    ]
