# Generated by Django 2.2.8 on 2020-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0004_auto_20200303_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
