# Generated by Django 2.2.8 on 2020-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0007_user_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='testname', max_length=64),
        ),
    ]
