"""
Django settings for first_dj project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 快速启动开发设置-不适合生产
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# 安全警告:对生产中使用的密匙保密!
SECRET_KEY = 'en1=+46l9sdyik1+xae_3&roijhqz9^0pfl*1($x%*6_1)c_!2'

# 安全警告:不要在生产环境中打开调试
DEBUG = True

# 配置自己的ip地址,
ALLOWED_HOSTS = []

# 这里面安装了哪些app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 创建一个app后,必须来这里注册
    'app1.apps.App1Config',
    'juheapp.apps.JuheappConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# 图片上传地址??
UPLOAD_PIC_DIR = os.path.join(BASE_DIR, 'resource', 'uploadpic')

# django中设置cookie过期时间
SESSION_COOKIE_AGE = 60 * 10

# 项目起始配置点
ROOT_URLCONF = 'first_dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'first_dj.wsgi.application'

# 数据库配置
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'slave': {
#         'ENGINE':'django.db.backends.mysql',
#         'NAME':'user_dj',
#         'USER':'root',
#         'PASSWORD':'12345678',
#         'HOST':'127.0.0.1',
#         'PORT':'3306',
#     }
# }

DATABASES={
    'default': {
        'ENGINE':'django.db.backends.mysql',
        'NAME':'user_dj',
        'USER':'root',
        'PASSWORD':'12345678',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    },
}
# 密码验证
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/


TIME_ZONE = 'Asia/Shanghai'

# 修改数据库时间
LANGUAGE_CODE = 'zh-hans'
# TIME_ZONE = 'Asia/Shanghai'
# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# UPLOAD_PIC_DIR
STATIC_URL = 'static/'
STATIC_ROOT_SELF = os.path.join(BASE_DIR, "static").replace('\\', '/')
# print(66666,STATIC_ROOT_SELF)
